//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolOfLanguageMetlin.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_CientInfo
    {
        public int ID { get; set; }
        public string IDGender { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastVizit { get; set; }
        public Nullable<int> qtyOfVizits { get; set; }
        public string Tags { get; set; }
    }
}
